#!/usr/bin/env python3
"""Pre-render publications and preprints into index.html from data/*.yml.

Crawlers and plain `curl` fetches don't execute JavaScript, so the publications
rendered client-side would be invisible to them. This script regenerates the
static HTML inside the PUBS:BEGIN/END and PREPRINTS:BEGIN/END markers in
index.html so the papers are visible without JS.

Usage:
    python build_pubs.py            # rewrite index.html in place
    python build_pubs.py --check    # exit non-zero if index.html is stale

Add/edit a paper by dropping a YAML file into data/, then rerun this script.
The client-side loader in index.html still runs in real browsers, so the
dynamic version will overwrite the static one with the freshest YAML content.
"""
from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path
from urllib.parse import quote

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required. Install with: pip install pyyaml")

ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"
INDEX = ROOT / "index.html"
COAUTHOR_FILE = DATA_DIR / "00_coauthor_profile.yml"

PUBS_BEGIN = "<!-- PUBS:BEGIN (auto-generated by build_pubs.py from data/*.yml; do not edit by hand) -->"
PUBS_END = "<!-- PUBS:END -->"
PREPRINTS_BEGIN = "<!-- PREPRINTS:BEGIN (auto-generated by build_pubs.py from data/*.yml; do not edit by hand) -->"
PREPRINTS_END = "<!-- PREPRINTS:END -->"

ME = "Weihang Guo"


def load_coauthors() -> dict[str, str]:
    profiles = yaml.safe_load(COAUTHOR_FILE.read_text())
    return {p["name"]: p["link"] for p in profiles if p.get("link")}


def load_papers() -> list[dict]:
    papers = []
    for yml in sorted(DATA_DIR.glob("*.yml")):
        if yml.name.startswith("00_"):
            continue
        doc = yaml.safe_load(yml.read_text())
        if doc:
            papers.append(doc)
    return papers


def format_authors(authors: list[str], coauthors: dict[str, str]) -> str:
    parts = []
    for author in authors:
        if author == ME:
            parts.append(f"<strong>{html.escape(ME)}</strong>")
        elif author in coauthors:
            parts.append(
                f'<a target="_blank" href="{html.escape(coauthors[author])}">'
                f'{html.escape(author)}</a>'
            )
        else:
            parts.append(html.escape(author))
    return ", ".join(parts)


def render_links(paper: dict) -> str:
    links = paper.get("links") or {}
    pid = paper["id"]
    out: list[str] = []

    arxiv = links.get("arxiv")
    if arxiv:
        out.append(
            f'<a target="_blank" href="https://arxiv.org/abs/{arxiv}">\n'
            f'                <img src="https://img.shields.io/badge/arXiv-{arxiv}-b31b1b.svg" alt="arXiv">\n'
            f'              </a>'
        )

    gh = links.get("github")
    if gh:
        out.append(
            f'<a target="_blank" href="https://github.com/{gh}">\n'
            f'                <img src="https://img.shields.io/badge/GitHub-{quote(gh, safe="")}-2ea44f.svg?logo=github" alt="GitHub">\n'
            f'              </a>'
        )

    if paper.get("abstract"):
        toggle = (
            f"document.getElementById('abs-{pid}').style.display = "
            f"document.getElementById('abs-{pid}').style.display === 'block' "
            f"? 'none' : 'block'"
        )
        out.append(
            f'<a onclick="{toggle}">\n'
            f'                <img src="https://img.shields.io/badge/Abstract-374151.svg" alt="Abstract">\n'
            f'              </a>'
        )

    if paper.get("bibtex"):
        toggle = (
            f"document.getElementById('bib-{pid}').style.display = "
            f"document.getElementById('bib-{pid}').style.display === 'block' "
            f"? 'none' : 'block'"
        )
        out.append(
            f'<a onclick="{toggle}">\n'
            f'                <img src="https://img.shields.io/badge/BibTeX-374151.svg" alt="BibTeX">\n'
            f'              </a>'
        )

    return "\n              ".join(out)


def render_paper(paper: dict, coauthors: dict[str, str]) -> str:
    pid = paper["id"]
    authors_html = format_authors(paper["authors"], coauthors)
    links_html = render_links(paper)

    footer_parts: list[str] = []
    if paper.get("venue"):
        footer_parts.append(
            f'<div class="pub-venue"><em>{html.escape(paper["venue"])}</em>, '
            f'{paper["year"]}</div>'
        )
    if paper.get("note"):
        footer_parts.append(f'<div class="pub-note">{paper["note"]}</div>')
    footer_parts.append(
        f'<div class="pub-links">\n              {links_html}\n            </div>'
    )
    footer_html = "\n            ".join(footer_parts)

    dropdowns: list[str] = []
    if paper.get("abstract"):
        abstract = paper["abstract"].strip().replace("\n", "<br>")
        dropdowns.append(
            f'<div class="pub-dropdown" id="abs-{pid}">\n'
            f'            <p><strong>Abstract:</strong> {abstract}</p>\n'
            f'          </div>'
        )
    if paper.get("bibtex"):
        bib = paper["bibtex"].strip().replace("<", "&lt;").replace(">", "&gt;")
        dropdowns.append(
            f'<div class="pub-dropdown" id="bib-{pid}">\n'
            f'<pre><code>{bib}</code></pre>\n'
            f'          </div>'
        )
    dropdown_html = ("\n          " + "\n          ".join(dropdowns)) if dropdowns else ""

    image = html.escape(paper.get("image", "images/favicon/android-chrome-192x192.png"))

    return (
        f'<article class="pub">\n'
        f'        <img class="pub-thumb" src="{image}" alt="paper thumbnail" '
        f'onerror="this.src=\'images/favicon/android-chrome-192x192.png\'" />\n'
        f'        <div class="pub-body">\n'
        f'          <div class="pub-title">{html.escape(paper["title"])}</div>\n'
        f'          <div class="pub-authors">{authors_html}</div>\n'
        f'          <div class="pub-footer">\n'
        f'            {footer_html}\n'
        f'          </div>{dropdown_html}\n'
        f'        </div>\n'
        f'      </article>'
    )


def render_section(papers: list[dict], coauthors: dict[str, str]) -> str:
    if not papers:
        return '<p style="color:var(--muted)">None currently listed.</p>'
    return "\n      ".join(render_paper(p, coauthors) for p in papers)


def replace_block(text: str, begin: str, end: str, body: str) -> str:
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(text):
        sys.exit(f"Could not find markers in index.html: {begin} ... {end}")
    replacement = f"{begin}\n      {body}\n      {end}"
    return pattern.sub(lambda _m: replacement, text)


def build(check: bool = False) -> int:
    coauthors = load_coauthors()
    papers = load_papers()
    papers.sort(key=lambda p: (p.get("year", 0), p.get("id", "")), reverse=True)

    pubs = [p for p in papers if p.get("type") == "published"]
    preprints = [p for p in papers if p.get("type") == "preprint"]

    pubs_html = render_section(pubs, coauthors)
    preprints_html = render_section(preprints, coauthors)

    original = INDEX.read_text()
    updated = replace_block(original, PUBS_BEGIN, PUBS_END, pubs_html)
    updated = replace_block(updated, PREPRINTS_BEGIN, PREPRINTS_END, preprints_html)

    if check:
        if updated != original:
            sys.stderr.write(
                "index.html is out of sync with data/*.yml. "
                "Run `python build_pubs.py` and commit the result.\n"
            )
            return 1
        print("index.html is up to date.")
        return 0

    if updated == original:
        print("index.html already up to date.")
    else:
        INDEX.write_text(updated)
        print(
            f"Rendered {len(pubs)} publication(s) and {len(preprints)} preprint(s) "
            f"into {INDEX.name}."
        )
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if index.html would change (useful in CI).",
    )
    args = parser.parse_args()
    sys.exit(build(check=args.check))


if __name__ == "__main__":
    main()
